# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOOK',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=32)),
                ('BookAuthor', models.CharField(max_length=32)),
                ('BookBrief', models.CharField(max_length=320)),
                ('BookPublish', models.CharField(max_length=32)),
                ('BookPrice', models.FloatField(default=0.0)),
                ('BookSell', models.FloatField(default=0.0)),
                ('Wechat', models.CharField(default='\u65e0', max_length=32)),
                ('TencentQQ', models.CharField(default='\u65e0', max_length=22)),
                ('CallOthers', models.CharField(default='\u65e0', max_length=32)),
                ('Lock', models.BooleanField(default=True)),
                ('Live', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BOOKIMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookImg', models.ImageField(upload_to='./upload/')),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_img', to='BookTrade.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='TRADE',
            fields=[
                ('TradeId', models.AutoField(primary_key=True, serialize=False)),
                ('TradeTime', models.DateField(auto_now_add=True)),
                ('TradeBrief', models.CharField(default='\u65e0', max_length=320)),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_trade', to='BookTrade.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='USR',
            fields=[
                ('USRId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('StuId', models.BigIntegerField()),
                ('PassWord', models.CharField(max_length=32)),
                ('Email', models.EmailField(max_length=254)),
                ('TelPhone', models.CharField(max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='USRIMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsrImg', models.ImageField(upload_to='./upload/')),
                ('UsrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr_img', to='BookTrade.USR')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='BuyerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_usr', to='BookTrade.USR'),
        ),
        migrations.AddField(
            model_name='book',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr_book', to='BookTrade.USR'),
        ),
    ]
