# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 15:31
from __future__ import unicode_literals

import ImageStorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimg',
            name='BookImg',
            field=models.ImageField(storage=ImageStorage.storage.ImageStorage(), upload_to='./img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='usrimg',
            name='UsrImg',
            field=models.ImageField(storage=ImageStorage.storage.ImageStorage(), upload_to='./img/%Y/%m/%d'),
        ),
    ]
