# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrade', '0002_auto_20170404_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOOKIMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookImg', models.ImageField(upload_to='upload')),
                ('BookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_img', to='BookTrade.BOOK')),
            ],
        ),
        migrations.CreateModel(
            name='USRIMG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UsrImg', models.ImageField(upload_to='upload')),
                ('UsrID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr_img', to='BookTrade.USR')),
            ],
        ),
    ]
