# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrade', '0003_bookimg_usrimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookimg',
            name='BookImg',
            field=models.ImageField(upload_to='./upload/'),
        ),
        migrations.AlterField(
            model_name='usrimg',
            name='UsrImg',
            field=models.ImageField(upload_to='./upload/'),
        ),
    ]
