# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrade', '0004_auto_20170407_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='BookPrice',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='book',
            name='BookSell',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='book',
            name='TencentQQ',
            field=models.CharField(default='\u65e0', max_length=22),
        ),
        migrations.AddField(
            model_name='book',
            name='Wechat',
            field=models.CharField(default='\u65e0', max_length=32),
        ),
    ]
