# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrade', '0005_auto_20170409_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='CallOthers',
            field=models.CharField(default='\u65e0', max_length=32),
        ),
    ]
