# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrade', '0006_book_callothers'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Lock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='TradeBrief',
            field=models.CharField(default='\u65e0', max_length=320),
        ),
    ]
