# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookTrade', '0007_auto_20170411_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Live',
            field=models.BooleanField(default=True),
        ),
    ]
