# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BookTrade', '0002_auto_20170427_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('ChatTime', models.DateField(auto_now_add=True)),
                ('manage', models.BooleanField(default=True)),
                ('Recver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat2_usr', to='BookTrade.USR')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat1_usr', to='BookTrade.USR')),
            ],
        ),
    ]
